package com.liz.auckland.util

class KEY {
    companion object {
        const val SAVED_DATA = "SAVED_DATA"
        const val CURRENT_TOWN_CITY = "CURRENT_TOWN_CITY"
        const val CURRENT_SUBURB_LOCALITY = "CURRENT_SUBURB_LOCALITY"
        const val CURRENT_ROAD_NAME = "CURRENT_ROAD_NAME"
        const val CURRENT_ADDRESS_NUMBER = "CURRENT_ADDRESS_NUMBER"
        const val NOTIFICATION_TITLE = "NOTIFICATION_TITLE"
        const val HOUSEHOLD_RUBBISH_FROM = "HOUSEHOLD_RUBBISH_FROM"
        const val HOUSEHOLD_RUBBISH_TO = "HOUSEHOLD_RUBBISH_TO"
        const val HOUSEHOLD_RECYCLING_FROM = "HOUSEHOLD_RECYCLING_FROM"
        const val HOUSEHOLD_RECYCLING_TO = "HOUSEHOLD_RECYCLING_TO"
        const val COMMERCIAL_RUBBISH_FROM = "COMMERCIAL_RUBBISH_FROM"
        const val COMMERCIAL_RUBBISH_TO = "COMMERCIAL_RUBBISH_TO"
        const val COMMERCIAL_RECYCLING_FROM = "COMMERCIAL_RECYCLING_FROM"
        const val COMMERCIAL_RECYCLING_TO = "COMMERCIAL_RECYCLING_TO"

    }
}